var const_shower_config = 1;
var const_date_time = 2;
var const_daylight_savings = 3;
var const_lang = 4;
var const_units = 5;
var const_power_off = 6;
var const_settings_lock = 7;
var const_steam_select = 8;
var const_massage = 9;
var const_spa = 10;
var const_relay_one_on_when = 11;
var const_relay_one_off_when = 12;
var const_relay_one_on_delay = 13;
var const_relay_one_on_delay_time = 14;
var const_relay_one_off_delay = 15;
var const_relay_one_off_delay_time = 16;
var const_relay_one_name = 17;
var const_contact_one_name = 18;
var const_contact_one_when_closed = 19;
var const_contact_one_when_open = 20;
var const_contact_one_on_delay = 21;
var const_contact_one_on_delay_time = 22;
var const_contact_one_off_delay = 23;
var const_contact_one_off_delay_time = 24;
var const_user_name = 25;
var const_clear_user_name = 26;
var const_auto_return = 27;
var const_interface_beep = 28;
var const_interface_name = 29;
var const_interface_auto_dim = 30;
var const_interface_start_screen = 31;
var const_valve_outlet_order = 32;
var const_valve_outlet_massage = 33;
var const_valve_outlet_default = 34;
var const_valve_outlet_flow = 35;
var const_valve_outlet_ramp = 36;
var const_valve_outlet_type = 37;
var const_valve_default_temp = 38;
var const_valve_max_temp = 39;
var const_valve_massage_order = 40;
var const_valve_auto_purge = 41;
var const_valve_cold_water = 42;
var const_music_volume = 43;
var const_music_treble = 44;
var const_music_bass = 45;
var const_music_balance = 46;
var const_music_BT_device = 47;
var const_music_BT_key = 48;
var const_music_BT_password = 49;
var const_light_name = 50;
var const_light_load_type = 51;
var const_light_fade_speed = 52;
var const_light_brightness = 53;
var const_light_delay_time = 55;
var const_light_delay_event = 56;
var const_steam_def_temp = 57;
var const_steam_max_temp = 58;
var const_steam_def_time = 59;
var const_steam_start_clean = 60;
var const_six_port_calibration_valve1 = 61;
var const_six_port_calibration_valve2 = 62;
var const_relay_two_on_when = 65;
var const_relay_two_off_when = 66;
var const_relay_two_on_delay = 67;
var const_relay_two_on_delay_time = 68;
var const_relay_two_off_delay = 69;
var const_relay_two_off_delay_time = 70;
var const_relay_two_name = 71;
var const_contact_two_name = 72;
var const_contact_two_when_closed = 73;
var const_contact_two_when_open = 74;
var const_contact_two_on_delay_time = 76;
var const_contact_two_off_delay_time = 78;
var const_rain_fade_speed = 79;
var const_rain_brightness = 80;
var const_rain_white_color = 81;
var const_rain_effect_speed = 82;
var const_outlet_auto_purge = 83;
var const_light_add_module = 84;
var const_light_del_module = 85;
var const_wifi_password = 86;
var const_wifi_security = 87;
var const_wifi_SSID = 88;
var const_hospitality = 89;
var const_date_format = 90;
var const_time_format = 91;
var const_dual_shower = 92;
var const_valve_deluge_default = 93;
var const_clear_input_name = 94;
var const_input_name = 95;
var const_custom_msg_Status = 96;   //added by TF team,22-04-2015
var const_userlock = 97; //Added by TF Team 07-07
var const_webpage_lock = 98; //Added by TF Team 07-07
var const_max_valve_runtime = 99;//Added by TF Team 07-07
var const_max_steam_runtime = 100;//Added by TF Team 07-07
var const_massage_clear = 101; // Added by TF-Team on 27-10-2015 for sending massage clear message to the cgi bug fix 1339
var const_spa_selection = 102; //Added by TF-Team on 17-11-2015 for spa selection on spa tab
var const_files_deletion = 103; //Added by TF-Team for file deletion in the webpage on 25-11-2015
var const_light_status_clear = 104; //Added by TF-Team to clear the light attach status after 60 secs if a module is not attached.
var const_light_remove_clear = 105; //Added by TF-Team to clear the light attach status after 60 secs if a module is not attached.